name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  go_router: ^10.1.1
  flutter_riverpod: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
